flowchart TD
    Account --> SEED1[Seed]
    SEED1 --> HD1[hd path]
    SEED1 --> CHAIN1[chain code]
    HD1 --> ETC1[...]
    CHAIN1 --> ETC1
    Account --> SEED2[Seed]
    SEED2 --> HD2[hd path]
    SEED2 --> CHAIN2[chain code]
    HD2--> ETC2[...]
    CHAIN2 --> ETC2
